//! @ Sometimes it is desirable to make horizontal or vertical rules line up
//! precisely with certain features in characters of a font. It is possible to
//! guarantee the correct matching between \.{DVI} output and the characters
//! generated by \MF\ by adhering to the following principles: (1)~The \MF\
//! characters should be positioned so that a bottom edge or left edge that is
//! supposed to line up with the bottom or left edge of a rule appears at the
//! reference point, i.e., in row~0 and column~0 of the \MF\ raster. This
//! ensures that the position of the rule will not be rounded differently when
//! the pixel size is not a perfect multiple of the units of measurement in
//! the \.{DVI} file. (2)~A typeset rule of height $a>0$ and width $b>0$
//! should be equivalent to a \MF-generated character having black pixels in
//! precisely those raster positions whose \MF\ coordinates satisfy
//! |0<=x<@t$\alpha$@>b| and |0<=y<@t$\alpha$@>a|, where $\alpha$ is the number
//! of pixels per \.{DVI} unit.
//! @:METAFONT}{\MF@>
//! @^alignment of rules with characters@>
//! @^rules aligning with characters@>
//!
