//! @ Pages are built by appending nodes to the current list in \TeX's
//! vertical mode, which is at the outermost level of the semantic nest. This
//! vlist is split into two parts; the ``current page'' that we have been
//! talking so much about already, and the ``contribution list'' that receives
//! new nodes as they are created.  The current page contains everything that
//! the page builder has accounted for in its data structures, as described
//! above, while the contribution list contains other things that have been
//! generated by other parts of \TeX\ but have not yet been
//! seen by the page builder.
//! The contribution list starts at |link(contrib_head)|, and it ends at the
//! current node in \TeX's vertical mode.
//!
//! When \TeX\ has appended new material in vertical mode, it calls the procedure
//! |build_page|, which tries to catch up by moving nodes from the contribution
//! list to the current page. This procedure will succeed in its goal of
//! emptying the contribution list, unless a page break is discovered, i.e.,
//! unless the current page has grown to the point where the optimum next
//! page break has been determined. In the latter case, the nodes after the
//! optimum break will go back onto the contribution list, and control will
//! effectively pass to the user's output routine.
//!
//! We make |type(page_head)=glue_node|, so that an initial glue node on
//! the current page will not be considered a valid breakpoint.
//!
//! @<Initialize the special list...@>=
//! type(page_head):=glue_node; subtype(page_head):=normal;
//!
