name: Build

on:
  push:
    branches:
      - master
      - feature/*
  pull_request:
    branches:
      - master
      - feature/*

env:
  CARGO_TERM_COLOR: always

jobs:
  linux-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --workspace --verbose
    - name: Run tests
      run: cargo test --workspace --verbose

  linux-build-with-statistics:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --workspace --features tex-cli/statistics --verbose
    - name: Run tests
      run: cargo test --workspace --features tex-cli/statistics --verbose

  windows-build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --workspace --verbose
    - name: Run tests
      run: cargo test --workspace --verbose

  windows-build-with-statistics:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --workspace --features tex-cli/statistics --verbose
    - name: Run tests
      run: cargo test --workspace --features tex-cli/statistics --verbose

  macos-build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --workspace --verbose
    - name: Run tests
      run: cargo test --workspace --verbose

  macos-build-with-statistics:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --workspace --features tex-cli/statistics --verbose
    - name: Run tests
      run: cargo test --workspace --features tex-cli/statistics --verbose
